#!/usr/bin/env python3

import re
from gradelib import *

r = Runner(save("xv6.out"))

@test(50, "oc-thread-test")
def test_thread():
    r.run_qemu(shell_script([
        'threadtest',
        'uthreadtest',
        'kthreadtest'
    ]), timeout=50)
    matches = re.findall("^TEST\d+ PASSED$", r.qemu.output, re.M)
    assert_equal(len(matches), 29, "thread test work")

run_tests()

